### ISSUE TITLE
Quantile calculation is wrong for most inputs

### ISSUE THREAD

**Issue by robsmith11** [vks/average#10]
I'm not sure what's going on in the quantile calculation, but it's producing results that aren't even close to being correct for most inputs.

For example, it calculates the 99th percentile (`p=0.99`) of
```
(0..10).into_iter().map(|x| x as f64)
```
as `6.0`.

The test case in the code happens to work, but almost all of the results on my data are wrong.

**Comment by vks** [comment]
Unfortunately the quantile calculation is the least tested part of the library. This might be a bug in the implementation. On other hand, the algorithm does not have an upper error bound. (In fact, it is not possible to calculate the quantiles in constant space with an upper error bound AFAIK.)

**Comment by vks** [comment]
See the [`quantiles`](https://crates.io/crates/quantiles) crate for algorithms trading space for better control of the error.

I will update the documentation to be clearer about the trade-offs.

**Comment by robsmith11** [comment]
Thanks.  I had just assumed it was an exact empirical quantile, but thinking about it now that is obviously impossible in constant space.
