### ISSUE TITLE
Implement FromParallelIterator

### ISSUE THREAD

**Issue by rasa200** [vks/average#16]
Hi authors!! Thank you very much for your great work!

I would like to ask for a new feature for greater interoperability: to implement the traits
- FromParallelIterator<f64>
- FromParallelIterator<&'a f64>

For now, I am doing the following:
```rust
let result: Variance = parallel_iterator.collect::<Vec<f64>>().iter().collect();
``` 

Cheers!

**Comment by vks** [comment]
About which `FromParallelIterator` trait are you talking? The one from the `rayon` crate?

**Comment by vks** [comment]
@rasa200 Does #17 work for you?

**Comment by rasa200** [comment]
Thank you for the quick reply!! (and sorry for being vague, yes, I meant the rayon crate).

It works perfectly!
