### ISSUE TITLE
Statistics for data sets with 0 or 1 element

### ISSUE THREAD

**Issue by jturner314-nrl** [vks/average#27]
Currently, the following example

```rust
use average::{Estimate, Mean, Variance};

fn main() {
    let m = Mean::new();
    println!("{}", m.mean());
    let mut v = Variance::new();
    println!("{}", v.sample_variance());
    v.add(5.);
    println!("{}", v.sample_variance());
}
```

prints

```
0
0
0
```

However, returning zero for these cases is misleading. I'd suggest returning `f64::NAN`, `None`, or `Err(_)`.

For a data set with 0 elements:

- The sample mean is undefined, since it requires division by 0:

   ```
        n
        ∑ xᵢ
       i=1     0
   x̅ = ――――― = ―
         n     0
   ```

- The sample variance is undefined, since it's defined in terms of deviations from the sample mean, and the sample mean is undefined.

For a data set with 1 element:

- The sample mean is the value of that element:

   ```
        n
        ∑ xᵢ
       i=1     x₁
   x̅ = ――――― = ―― = x₁
         n     1
   ```

- The sample variance is undefined, since it requires division by 0:

   ```
         n
         ∑ (xᵢ−x̅)²
        i=1          (x₁−x₁)²   0
   s² = ―――――――――― = ―――――――― = ―
          n − 1         0       0
   ```

What are your thoughts?

**Comment by vks** [comment]
This is intentional (and for the mean documented), but I'm open to return other values than 0. `NAN` seems like the best alternative.

For the mean, returning 0 is convenient, because it avoids having to a add a branch, but the performance difference is probably not important.

In any case, the behavior of the variance for `len < 2` should be documented.

**Comment by vks** [comment]
> A branch is necessary only in the implementation of .mean(). Since it doesn't affect the inner loop (the addition of data), the cost should pretty much always be negligible.

I agree. :+1: 

> Would you like me to submit a PR which changes the outputs to NAN?

Sure, that would be very welcome! There will be a bit of churn, because quite a few of the tests have to be adapted.
