### ISSUE TITLE
ability to persist serde or to build from parts.

### ISSUE THREAD

**Issue by Eh2406** [vks/average#6]
I am building an application that tracks some processing statistics using this library. I'd like to save these stats to disk to use the next time the app is opened. I see two mutually compatible solutions.

1. `from_raw_parts` functions, so for example I could rebuild a `Variance` from `N`, `Mean`, and `Variance`.
2. add an optional feature of serde support so I can serialize them direct to my json configuration.

Thoughts?

**Comment by vks** [comment]
I think the easiest and most conventional solution is optional serde support behind a feature.

**Comment by vks** [comment]
This has been implemented some time ago.
